{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "myblog.fullname" . }}
  labels:
    {{- include "myblog.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/issuer: {{ .Values.issuer.name }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostName }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - backend:
              serviceName: {{ include "myblog.fullname" . }}
              servicePort: {{ .Values.service.port }}
            path: /
{{- end }}
